spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: loli
    password: 12358
    url: jdbc:mysql://127.0.0.1:3306/sell?useSSL=true&characterEncoding=UTF-8

  jpa:
    show-sql: true

  jackson:
    default-property-inclusion: non_null

#server:
#  servlet:
#    context-path:
