spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: loli
    password: 12358
    url: jdbc:mysql://127.0.0.1:3306/sell?useSSL=true&characterEncoding=UTF-8

  jpa:
    show-sql: true

  jackson:
    default-property-inclusion: non_null

  redis:
    host: 127.0.0.1
    port: 6379

#server:
#  servlet:
#    context-path:

server:
  servlet:
    context-path: /sell

wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 47ccc303338cee6e62894fxxxxxxxxxxx
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

project-url:
  wechatMpAuthorize: http://localhost:8080
  wechatOpenAuthorize: http://sell.natapp4.cc
  sell: http://sell.natapp4.cc

# mybatis 设置日志输出可以这么搞
logging:
  level:
    com.bfchengnuo.sell.dao: debug
